config/routes.rb
Hrapp::Application.routes.draw do

 resources :imports,:only=>[:new, :create]
 resources :search ,:only=>[:index]
 resources :hr_wikis
 root :to => 'imports#new'
end

app/models/hr_wiki.rb
class HrWiki < ActiveRecord::Base
  attr_accessible :term, :definition
  validates :term, :definition,:presence=>true
 
end

app/models/import.rb
class Import < ActiveRecord::Base
  attr_accessible :attachment
  has_attached_file :attachment,
    :path => ":rails_root/public/:class/:attachment/:id/:style_:basename.:extension"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/hr_wikis_controller.rb
class HrWikisController < ApplicationController
  def index
    @hr_wikis=HrWiki.all
  end
  
  def show
    @hr_wiki=HrWiki.find params[:id]
  end
  
  def new
    @hr_wiki = HrWiki.new
    @hr_wikis = HrWiki.all
  end
  
  def create
    @hr_wiki=HrWiki.new(params[:hr_wiki])
    @hr_wikis = HrWiki.all
    if @hr_wiki.save
      redirect_to new_hr_wiki_path,:notice=>"Data saving successful"
    else
      render :new
    end
  end
  
  def edit
    @hr_wiki=HrWiki.find params[:id]
  end
  
  def update
    @hr_wiki=HrWiki.find params[:id]
    @hr_wiki.update_attributes(params[:hr_wiki])
    if @hr_wiki.save
      redirect_to new_hr_wiki_path,:notice=>"Data saving successful"
    else 
      render :edit
    end
  end
  
  def destroy
     @hr_wiki=HrWiki.find params[:id]
     if @hr_wiki.destroy
       redirect_to new_hr_wiki_path
     else 
        redirect_to new_hr_wiki_path,:notice=>"Data could not deleted"
     end
  end
end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController
require 'spreadsheet'
  def new
    @import = Import.new
  end
  
  def create
    @import = Import.new(params[:import])
    if @import.save
      Spreadsheet.client_encoding = 'UTF-8'
      book = Spreadsheet.open @import.attachment.path(:original)
      sheet0 = book.worksheet 0
      sheet0.each 1 do |row|
        hr_wiki = HrWiki.new()
        hr_wiki.term = row[0]
        hr_wiki.definition = row[1]
        hr_wiki.save
      end
      redirect_to root_url, :notice=>" Import has been succesfull." and return 
    else
      redirect_to root_url, :notice=>" Import has been unsuccesfull." and return 
    end
  end
 
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
    q="%#{params[:keyword]}%"
    @results=HrWiki.all(:conditions=>["lower(term) like ?",q.downcase])
    respond_to do |format|
      format.html  {render :text => "text to render..."}
      format.json  { render :text => params[:callback]+"("+@results.map(&:attributes).to_json+");" }
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hr_wikis_helper.rb
module HrWikisHelper
end

app/helpers/imports_helper.rb
module ImportsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/hr_wikis/_form.html.erb
<%= form_for @hr_wiki, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :term, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :term, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :definition, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :definition, :class => 'text_area' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                hr_wikis_path, :class => 'btn' %>
  </div>
<% end %>

app/views/hr_wikis/edit.html.erb
<%- model_class = HrWiki -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/hr_wikis/index.html.erb
<%- model_class = HrWiki -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:term) %></th>
      <th><%= model_class.human_attribute_name(:definition) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @hr_wikis.each do |hr_wiki| %>
      <tr>
        <td><%= link_to hr_wiki.id, hr_wiki_path(hr_wiki) %></td>
        <td><%= hr_wiki.term %></td>
        <td><%= hr_wiki.definition %></td>
        <td><%=l hr_wiki.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_hr_wiki_path(hr_wiki), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      hr_wiki_path(hr_wiki),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_hr_wiki_path,
            :class => 'btn btn-primary' %>

app/views/hr_wikis/new.html.erb
<%- model_class = HrWiki -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/hr_wikis/show.html.erb
<%- model_class = HrWiki -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:term) %>:</strong></dt>
  <dd><%= @hr_wiki.term %></dd>
  <dt><strong><%= model_class.human_attribute_name(:definition) %>:</strong></dt>
  <dd><%= @hr_wiki.definition %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              hr_wikis_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_hr_wiki_path(@hr_wiki), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              hr_wiki_path(@hr_wiki),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/imports/_form.html.erb
<%= form_for @import, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :attachment, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :attachment, :class => 'text_field' %>
    </div>
  </div>


  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                imports_path, :class => 'btn' %>
  </div>
<% end %>

app/views/imports/edit.html.erb
<%- model_class = Import -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/imports/index.html.erb
<%- model_class = Import -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:attachment_file_name) %></th>
      <th><%= model_class.human_attribute_name(:attachment_content_type) %></th>
      <th><%= model_class.human_attribute_name(:attachment_file_size) %></th>
      <th><%= model_class.human_attribute_name(:attachment_updated_at) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @imports.each do |import| %>
      <tr>
        <td><%= link_to import.id, import_path(import) %></td>
        <td><%= import.attachment_file_name %></td>
        <td><%= import.attachment_content_type %></td>
        <td><%= import.attachment_file_size %></td>
        <td><%= import.attachment_updated_at %></td>
        <td><%=l import.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_import_path(import), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      import_path(import),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_import_path,
            :class => 'btn btn-primary' %>

app/views/imports/new.html.erb
<%- model_class = Import -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/imports/show.html.erb
<%- model_class = Import -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:attachment_file_name) %>:</strong></dt>
  <dd><%= @import.attachment_file_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:attachment_content_type) %>:</strong></dt>
  <dd><%= @import.attachment_content_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:attachment_file_size) %>:</strong></dt>
  <dd><%= @import.attachment_file_size %></dd>
  <dt><strong><%= model_class.human_attribute_name(:attachment_updated_at) %>:</strong></dt>
  <dd><%= @import.attachment_updated_at %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              imports_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_import_path(@import), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              import_path(@import),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Hrapp" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

   
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Hrapp</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span9">
              <%= yield %>
            </div>
            <div class="span3">
              <div class="well sidebar-nav">
                <h3>Sidebar</h3>
                <ul class="nav nav-list">
                  <li class="nav-header">Sidebar</li>
                  <li><%= link_to "Link1", "/path1"  %></li>
                  <li><%= link_to "Link2", "/path2"  %></li>
                  <li><%= link_to "Link3", "/path3"  %></li>
                </ul>
              </div><!--/.well -->
            </div><!--/span-->
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>